# Generated by Django 3.2.4 on 2021-06-15 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendors', '0003_remove_products_user'),
        ('Signup', '0003_customer_model_user_type'),
    ]

