# Generated by Django 3.2.4 on 2021-06-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Signup', '0003_customer_model_user_type'),
        ('Vendors', '0004_products_product_quantity'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='Vendors.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signup.user_model')),
            ],
        ),
    ]
