# Generated by Django 3.2.4 on 2021-06-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0004_products_product_quantity'),
        ('Signup', '0003_customer_model_user_type'),
        ('Customer', '0004_alter_wishlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendors.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signup.customer_model')),
            ],
        ),
    ]
