# Generated by Django 3.2.4 on 2021-06-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rate',
        ),
    ]
