# Generated by Django 3.2.4 on 2021-07-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_auto_20210630_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='update_at',
        ),
    ]
