# Generated by Django 3.2.4 on 2021-06-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Signup', '0003_customer_model_user_type'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=50)),
                ('ad_price', models.IntegerField(default=0)),
                ('ad_condition', models.CharField(default='', max_length=50)),
                ('ad_description', models.CharField(default='', max_length=200, null=True)),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('ad_location', models.CharField(max_length=50)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.categories')),
                ('subcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.sub_categories')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Signup.user_model')),
            ],
            options={
                'db_table': 'used_products_tbl',
            },
        ),
    ]
