# Generated by Django 3.2.4 on 2021-06-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_products',
            name='subcategory',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.sub_categories'),
        ),
    ]
