# Generated by Django 3.2.4 on 2021-06-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_used_products_ad_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_products',
            name='ad_price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
