# Generated by Django 3.2.4 on 2021-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=500, null=True)),
                ('confirm_password', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
