# Generated by Django 3.2.4 on 2021-06-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0003_customer_model_user_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_model',
            table='users_tbl',
        ),
    ]
