# Generated by Django 3.2.4 on 2021-06-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0002_auto_20210612_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
