# Generated by Django 3.2.4 on 2021-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0004_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
