# Generated by Django 3.2.4 on 2021-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0005_products_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=1),
        ),
    ]
