# Generated by Django 3.2.4 on 2021-06-16 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Signup', '0003_customer_model_user_type'),
        ('Vendors', '0003_remove_products_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('postcode', models.CharField(default='', max_length=15)),
                ('city', models.CharField(default='', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signup.customer_model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendors.products')),
            ],
        ),
    ]
