# Generated by Django 3.2.4 on 2021-06-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0003_remove_products_user'),
        ('Order', '0004_rename_products_order_details_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vendors.products'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order_details',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vendors.store'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
    ]
