# Generated by Django 3.2.4 on 2021-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20210617_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_id',
            field=models.IntegerField(default=1),
        ),
    ]
