# Generated by Django 3.2.4 on 2021-06-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
