# Generated by Django 3.2.4 on 2021-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='status',
            field=models.CharField(default='Order is not Confirmed Yet.', max_length=50),
        ),
    ]
