# Generated by Django 3.2.4 on 2021-06-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_order_details_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order_tbl',
        ),
        migrations.AlterModelTable(
            name='order_details',
            table='Order_details_tbl',
        ),
    ]
