# Generated by Django 3.2.4 on 2021-07-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20210630_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
